version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "/usr/local/etc/mysqlContain/log/:/var/log/"
      - "/usr/local/etc/mysqlContain/data/:/var/lib/mysql/"
      - "/usr/local/etc/mysqlContain/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - "3306:3306"
  nginx:
    container_name: nginx
    image: nginx:stable
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /root/item-service/nginx/html/:/usr/share/nginx/html/
      - /root/item-service/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "48099:80"
  redisStandalonoe:
    container_name: redisalone
    image: redis:7.0.4-alpine3.16
    volumes:
      - /usr/local/etc/redisContain/redisStandalone/conf:/usr/local/etc/redis
      - /usr/local/etc/redisContain/redisStandalone/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "8008:8008"
  canalServer:
    container_name: canalServer
    image: canal/canal-server:v1.1.6
    environment:
      canal.destinations: heima
      canal.instance.master.address: mysql:3306
      canal.instance.dbUsername: canal
      canal.instance.dbPassword: canal
      canal.instance.connectionCharset: UTF-8
      canal.instance.tsdb.enable: true
      canal.instance.gtidon: false
      canal.instance.filter.regex: heima\\..* \
    ports:
      - "11111:11111"
  openresty:
    container_name: openresty
    image: openresty/openresty:1.21.4.1-3-centos-rpm
    volumes:
      - /root/item-service/nginx/openresty/openresty_nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /root/item-service/nginx/openresty/lua:/usr/local/openresty/nginx/lua
      - /root/item-service/nginx/openresty/lua/common.lua:/usr/local/openresty/lualib/common.lua
    ports:
      - "8081:8081"
